import { ICidadeResponse } from "./CidadeResponse";
import { IEstadoResponse } from "./EstadoResponse";
import { IPaisResponse } from "./PaisResponse";
import { IUsuarioResponse } from "./UsuarioResponse";

export interface IFuncionarioResponse {
  id: string;
  codInterno: number;
  ativo: boolean;
  isCliente: boolean;
  isFornecedor: boolean;
  isTransportadora: boolean;
  isFuncionario: boolean;
  tipoPessoa: string;
  nome: string;
  razaoSocial: string;
  apelido: string;
  cpfCnpj: string;
  ieIndicador: number;
  rg: string;
  rgOrgao: string;
  rgDataEmissao: string | null;
  dataNascimento: string | null;
  endereco: string;
  numero: string;
  bairro: string;
  referencia: string;
  cep: string;
  cidade: ICidadeResponse;
  estado: IEstadoResponse;
  pais: IPaisResponse;
  contato1: string;
  contato2: string;
  contato3: string;
  email: string;
  email2: string;
  paisNacionalidade: IPaisResponse;
  cidadeNaturalidade: ICidadeResponse | null;
  estadoNaturalidade: IEstadoResponse | null;
  filiacaoPai: string;
  filiacaoPaiContato: string;
  filiacaoMae: string;
  filiacaoMaeContato: string;
  filiacaoEndereco: string;
  filiacaoNumero: string;
  filiacaoBairro: string;
  filiacaoReferencia: string;
  filiacaoCep: string;
  cidadeFiliacao: ICidadeResponse | null;
  estadoFiliacao: IEstadoResponse | null;
  conjugeNome: string;
  conjugeCpf: string;
  conjugeRg: string;
  conjugeDataNascimento: string | null;
  conjugeContato: string;
  conjugeEndereco: string;
  conjugeNumero: string;
  conjugeBairro: string;
  conjugeCep: string;
  cidadeConjuge: ICidadeResponse | null;
  estadoConjuge: IEstadoResponse | null;
  conjugeEmpresa: string;
  conjugeEmpresaCargo: string;
  conjugeEmpresaRenda: number;
  conjugeEmpresaAdmissao: string | null;

  funcionarioStatus: string;
  funcionarioCtps: string | null;
  funcionarioSalario: number | null;
  funcionarioDataAdmissao: string | null;
  funcionarioDataDemissao: string | null;
  funcionarioDataAfastamento: string | null;

  sexo: string;
  estadoCivil: string;
  obs: string;
  datahoraCadastro: string;
  usuario: IUsuarioResponse;
}
